### ISSUE TITLE
Shortlist Potential Graphing Library

### ISSUE THREAD

**Issue by dareid** [ALDLife/outcome-graph#1]
Detail potential graphing libraries to use for the radar chart. Ideally it would be free and have a suitable open source license. 

Highlight your preferred option.

**Comment by themakshter** [comment]
# Data Visualisation Libraries Research

## Resources

- [Wikipedia page on JS Charting Frameworks Comparison](https://en.wikipedia.org/wiki/Comparison_of_JavaScript_charting_frameworks)
- [Udacity's 12 best charting libraries for web developers](http://blog.udacity.com/2016/03/12-best-charting-libraries-for-web-developers.html)
- [TNW's 20 best js charting libraries](https://thenextweb.com/dd/2015/06/12/20-best-javascript-chart-libraries/)
- [Guide on picking best charting library - FusionCharts](http://www.fusioncharts.com/javascript-charts-guide/)
- [Choosing a charting library - ZingChart](https://blog.zingchart.com/2015/09/15/how-to-choose-a-javascript-charting-library/)
- [FusionCharts' library comparisons](http://www.fusioncharts.com/javascript-charting-comparison/)
- [Why choose commercial library over open-source one](https://www.codeproject.com/articles/581146/8-reasons-to-choose-commercial-library-instead-of)

## Requirements

- Specify tooltips on the values
- Show atleast 10 axes (more is better)
- Show atleast 8 series 
- API for hiding/showing series for session selector, instead of redrawing the whole graph all the time
- Handle missing data points on a series
- Cross-browser support
- Cross-device support

## Decision

- [Charts.js](http://www.chartjs.org/) - [GitHub](https://github.com/chartjs/Chart.js)- 28k stars
    + [Radar example](http://www.chartjs.org/docs/#radar-chart)
    + Open source
    + has components for numerous view components (Angular, Vue, React)
    + [Support for canvas](http://caniuse.com/#feat=canvas)
    + Requirements
        * [x] Tooltips
        * [x] 10 axes min
        * [x] 8 series min
        * [x] Hiding/showing series dynamically
        * [x] Handle missing data
        * [x] Cross-browser
        * [x] Cross-device
    + [Prototyping](https://codepen.io/themakshter/pen/VpPGzv)
        * Pros
            - All the requirements are met
            - Good visual
            - Simple to follow the code
        * Cons
            - Documentation is good, but no links to get an example going or play with the code. Have to search for it on GitHub
            - Custom tooltip formatter is a bit of a pain to do, but manageable
    + **Accepted by client**

## Rejections

- ~~[ECharts](https://ecomfe.github.io/echarts-doc/public/en/index.html) - [GitHub](https://github.com/ecomfe/echarts) - 17k stars~~ _(some limitations related to requirements - moreover, it doesn't handle missing data gracefully)_
    + [Radar example](https://ecomfe.github.io/echarts-examples/public/index.html#chart-type-radar)
    + chinese library
    + seemingly popular
    + has components for numerous view components (Angular, Vue, React)
    + quite comprehensive
    + open source
    + BSD licence
    + Requirements
        * [x] Tooltips
        * [x] 10 axes min
        * [x] 8 series min
        * [x] Hiding/showing series dynamically
        * [ ] Handle missing data
        * [x] Cross-browser
        * [x] Cross-device
    + [Prototyping](https://codepen.io/themakshter/pen/OppMPN)
        * Pros
            - Excellent documentation
            - Easy to demo and play with code
        * Cons
            - Bugged for missing data (breaks if the first item isn't complete and remaining complete data items don't get drawn)
            - No way to have tool tip for a particular data item for one radar chart, its object contains all values so no way to know what item was looked at
- ~~[D3](https://d3js.org/) - [Github](https://github.com/d3/d3) - 61k stars~~ _(options for radar chart not general or robust enough for use)_
    + Radar examples
        * [Reusable radar chart implementation](http://bl.ocks.org/tpreusse/2bc99d74a461b8c0acb1) - [GitHub](https://github.com/tpreusse/radar-chart-d3)
        * [Improvement on radar-chart-d3](http://bl.ocks.org/nbremer/6506614)
        * [Variation of the above as interactive radar chart](http://bl.ocks.org/chrisrzhou/2421ac6541b68c1680f8)
        * [Redesign of radar chart](http://bl.ocks.org/nbremer/21746a9668ffdf6d8242)
    + Probably the most powerful and popular visualisation library
        * lots of libraries build on top of it
    + but pain to work with as-is
    + Open source
    + BSD-3 clause
    + Requirements
        * [x] Tooltips
        * [x] 10 axes min
        * [x] 8 series min
        * [x] Hiding/showing series dynamically _(will have to do it ourselves - [possible solution](http://bl.ocks.org/d3noob/5d621a60e2d1d02086bf))_
        * [ ] Handle missing data
        * [x] Cross-browser
        * [x] Cross-device
- ~~[FusionCharts](http://www.fusioncharts.com/)~~ _(there is no free version available - only discount for non-profts)_
    + [Radar example](http://www.fusioncharts.com/charts/radar-spider-charts/)
    + [Free version comes with watermark, have to pay for removal](http://www.fusioncharts.com/download/)
    + [30% discount for NGOs](http://www.fusioncharts.com/buy/faqs/)
- ~~[Highcharts](http://www.highcharts.com/)~~ _(free for non-profit but not compatible with open source licences)_
    + [Radar example](http://www.highcharts.com/demo/polar-spider)
    + [Priced, but free for non-profits under CC licence](https://shop.highsoft.com/faq#Non-Commercial-0)
        * "Although Highsoft´s Software have open source codes, our software is not licensed as an open source software and are unfortunately not compatible with any open source software license like Apache 2 or any GPL. See also Non-Commercial Redistribution"
    + Requirements
        * [x] Tooltips
        * [x] 10 axes min
        * [x] 8 series min
        * [x] Hiding/showing series dynamically
        * [ ] Handle missing data
        * [x] Cross-browser
        * [x] Cross-device
- ~~[AnyChart](http://www.anychart.com/)~~ _(Probably not worth the trouble with pricing)_
    + [Free licence for non-profits](http://www.anychart.com/buy/url/?education)
    + [Radar example](http://www.anychart.com/products/anychart/gallery/Radar_Charts_(Spiderweb)/)
        * [Docs](https://docs.anychart.com/Basic_Charts/Radar_Plot/Overview)
    + Requirements
        * [x] Tooltips
        * [x] 10 axes min
        * [x] 8 series min
        * [x] Hiding/showing series dynamically
        * [ ] Handle missing data
        * [x] Cross-browser
        * [x] Cross-device
- ~~[plotly.js](https://plot.ly/javascript/) - [Github](https://github.com/plotly/plotly.js) - 6k stars~~ _(don't have suitable radar chart)_
    + Open source
    + MIT Licence
    + Not exactly radar graph chart, but close
        * [Wind rose chart](https://plot.ly/javascript/wind-rose-charts/)
        * [Polar chart](https://plot.ly/javascript/polar-chart/)
- ~~[ZingChart](https://www.zingchart.com/)~~ _(there is no free version available - only discount for non-profts)_
    + [Radar example](https://www.zingchart.com/docs/chart-types/radar-charts/)
    + [Free version comes with watermark, have to pay for removal](https://www.zingchart.com/buy/)
    + Probably discount price for non-profit. Email at sales@zingchart.com for details
- ~~[AmCharts](https://www.amcharts.com/)~~ _(Seems mostly a discount, not a free version)_
    + [Radar example](https://www.amcharts.com/demos/radar-chart/)
    + [Free version comes with watermark, have to pay for removal](https://www.amcharts.com/online-store/)
        * Possible help for 'cash-strapped start-ups' but probably a discount
    + [Radar example](http://www.amcharts.com/demos/radar-chart/)
- ~~[jChartFx](http://www.jchartfx.com/default.aspx)~~ _(Features don't seem that great and licensing is tricky)_
    + [Radar example](http://support.softwarefx.com/jChartFX/article/2501514#!2501023)
    + [Free version comes with watermark, have to pay for removal](http://www.jchartfx.com/pricing.aspx)
        * [Licence for free version](http://www.jchartfx.com/eula/default.aspx)
- ~~[Rgraph](https://www.rgraph.net/)~~ _(decent enough library but has some rough edges)_
    + [Radar example](https://www.rgraph.net/demos/index.html#svg) (search for radar)
    + MIT Licence
    + Open source but can't seem to find the code on github
    + Requirements
        * [x] Tooltips
        * [x] 10 axes min
        * [x] 8 series min
        * [ ] Hiding/showing series dynamically
        * [ ] Handle missing data
        * [x] Cross-browser
        * [x] Cross-device
- ~~[Webix](http://webix.com/widget/charts/)~~ _(charts are small part of the library so not as polished as others)_
    + [Radar example](http://docs.webix.com/desktop__radar_chart.html)
    + [GPL v3 standard licence with fewer features](http://webix.com/licenses/)
- ~~[DevExtreme](https://js.devexpress.com/Overview/Charts/)~~ _( no free version for non-profts as well as being overkill for requirements)_
    + [Radar example](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/SpiderWeb/jQuery/Light/)
    + Is a huge suite and very suitable for big corps
    + Cannot find a free licence or non-profit exception
    + probably overkill
-  ~~[DHTMLX Charts](https://dhtmlx.com/docs/products/dhtmlxChart/)~~ _(charts are a small component - not a speciality)_
    + [Radar example](https://dhtmlx.com/docs/products/dhtmlxChart/) - look for Radar charts
    + [Free with GNU GPL v2 Licence](https://dhtmlx.com/docs/products/licenses.shtml)
        * With watermark
- ~~[ShieldUI](http://www.shieldui.com/products/chart)~~ _(looks neat enough, but charts aren't a specialty and it shows)_
    + [Free for non-commercial use](http://www.shieldui.com/purchase)
    + Radar links
        * [Polar line](https://demos.shieldui.com/web/polarline-chart/basic-usage)
        * [Polar area](https://demos.shieldui.com/web/polararea-chart/basic-usage)

**Comment by themakshter** [comment]
[Codepen for Chart.js using data from the requirements page](https://codepen.io/themakshter/pen/VpPGzv)

[Codepen for ECharts3 using data from the requirements page](https://codepen.io/themakshter/pen/OppMPN)

Pros and cons added for prototyping in the main comment above

**Comment by themakshter** [comment]
**Chart.js** has been chosen as the visualisation library. Closing this now.
